### ISSUE TITLE
Unprotect attack does not work

### ISSUE THREAD

**Issue by c5s** [RUB-NDS/MS-RMS-Attacks#1]
When running the unprotect attack I am getting the following error (in German):

```
Der Threadmodus kann nicht nach dem Einstellen geändert werden.
Die Anwendung hat beim Aufrufen des Rights Management-Diensts kein Schlüsselhandle bereitgestellt. Wenden Sie sich an den technischen Support für die Anwendung, um weitere Unterstützung zu erhalten.
Falscher Parameter.
```
Translated to English:

```
Cannot change thread mode after it is set.
The application must provide a key handle to access the requested information. Contact your application support for further investigation.
The parameter is incorrect.
```

**Comment by wenry55** [comment]
change the line just below main() function in decrypter.cpp.
=> char * license = new char[50000]  to 70000 or more.
I thinkk some documents with (Azure)RMS has bigger size of licese than 50,000.

**Comment by Kaedo** [comment]
Did it helped to increase the number of chars in the decrypter.cpp?

**Comment by c5s** [comment]
Sorry, I was busy working on other projects.
Increasing the char array size did not help (I tested it with 500,000).
After the above error message it says:
```
Unbehandelte Ausnahme: System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
  bei decryptEnrcyptedContent(Stream encryptedStream) in c:\users\administrator\ms-rms-attacks\decrypter\decrypter\decrypter.cpp:Zeile 174
  bei initDecryption(Byte[] encryptedBytes) in c:\users\administrator\ms-rms-attacks\decrypter\decrypter\decrypter.cpp:Zeile 174
  bei main() in c:\users\administrator\ms-rms-attacks\decrypter\decrypter\decrypter.cpp:Zeile 396.
  bei mainCRTStartup()
```
Do you have any idea why it is not working?

I noticed that Microsoft updated the RMS SDK on 21.02.2017. Version number of the exe is 1.0.3102.221. Maybe they fixed the attack? Unfortunately I could not find an older release. Could you please provide the SDK that works for you?

**Comment by Kaedo** [comment]
I will take a look for the older release and get back.

**Comment by Kaedo** [comment]
Ok, you can find the RMS SDK executables we used in the respository. Let me know if this fixed the error.

**Comment by c5s** [comment]
Thank you! Unfortunately it still does not work.
Any ideas? I am using Windows 7 64 bits and Visual Studio Community 2015. I followed https://github.com/MicrosoftDocs/Azure-RMSDocs/blob/master/Azure-RMSDocs/develop/how-to-configure-a-visual-studio-project-to-use-the-ad-rms-sdk-2-0.md to configure the project. For creating the x64 release I also had to add advapi32.lib to the linker dependencies.
Interestingly only the x64 build throws a NullReferenceException but the error is the same.

I could send you my file by private e-mail if you promise not to pass it to someone else. It would be great if you could have a look at it. Can I send it to your RUB e-mail address?

**Comment by Kaedo** [comment]
Are you using the domain user account, which have view (read) access to the azure RMS protected file, to execute the unprotect.exe?

**Comment by c5s** [comment]
My computer is not inside a domain. I am using Active Directory Federation Services. If I open an document a browser window pops up where I enter my credentials (SSO). This only happens for the first time as long as I leave Word open. I opened the document before executing decrypter.exe to make sure that my credentials are cached.
Are documents that use federation not supported?

**Comment by Kaedo** [comment]
We never tested it with active directory federation, we always were in the domain of our test setup.
From your description it could also be the case, I assume, that every attempt to open a document needs the ADFS login procedure, in order to get the use-license. This is needed if use license caching is deactivated.

So I can not help you. But you could try it by yourself, the code is there.

PS: I also want to remind, that the code was published for research purpose only.

**Comment by 59e5aaf4** [comment]
For research as well, nowadays WINWORD.EXE doesn't even use `msipc.dll!IpcGetKey`, but they still use a handful of `msipc.dll` functions, including `IpcProtectWindow`. Breakpointing on it, replacing first opcodes with `C3` ( RET ), will accidentally allow you to screenshot word without having a black output. Also, `IpcDecrypt` isn't even used at all, and when the system is loaded there's no PKZIP+XML in RAM anywhere. It's still possible (obviously) to grep for specific text in RAM and copy-paste text manually, but no easy content recovery that way. In a corp environment for unknown reasons IpcGetKey would fail ( see below ) while word, without using this function, decrypts content. Surely they changed their API, there are a bunch of smaller DLLs named "msip*" getting loaded.

```
Unhandled Exception: System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at IpcGetKey(_IPC_BUFFER* , UInt32 , _IPC_PROMPT_CTX* , Void* , IPC_KEY_HANDLE__** )
   at readLicense(Stream encryptedStream)
   at initDecryption(Byte[] encryptedBytes)
   at main()
   at _mainCRTStartup()
   
```

Thanks for the good work !
