### ISSUE TITLE
It works with docx, but not work with doc (2003) word documents

### ISSUE THREAD

**Issue by helloword222** [RUB-NDS/MS-RMS-Attacks#5]
My findings : 
The .doc structure is different than .docx, and that’s the reason.
In docx file structure, there is file called EncryptedDocument which is not existing in case of .doc file whereas in .doc file structure there is file called WordDocument

Inside decrypter.cpp
I changed the followings :

- line 189 : dateiname = "decrypted.docx" to dateiname = "decrypted.doc"
- replace "EncryptedDocument" with "WordDocument"
- replace the path to "[6]Primary" file as the follwoing : "[6]DataSpaces\TransformInfo\[9]DRMTransform" instead of the old value (the path inside .docx file)

and rebuild a new **exe** 

I got the output file which is not working.
Any help please

**Comment by Kaedo** [comment]
I will check it and come back to you later.
